### ISSUE TITLE
publish only ros_extensions

### ISSUE THREAD

**Issue by hyansuper** [Affonso-Gui/scratch3-ros-vm#3]
Hi, 
Thanks for this Ros extension, it's going to expand the possiblity of scratch controlling so many robots!
My problem is: I have already git-cloned scratch-vm and scratch-gui from LLK's repository and added some custom extensions. Can I only copy the src/extensions/scratch3_ros folder to my extensions folder without git clone this whole project if unnecessary?
I think it would be nice if you only publish those files that needs to be added or updated.

**Comment by Affonso-Gui** [comment]
Hello,

Probably you can have some functional features by copying the scratch3_ros directory and adding it to the scratch extensions, but it will not be fully functional (e.g. I had to make some changes to display message slots into the viewport, to show the connection window properly, etc).

My suggestion is to clone this repository and work on your custom extensions on top of it (importing [RosUtil.js](https://github.com/Affonso-Gui/scratch3-ros-vm/blob/develop/src/extensions/scratch3_ros/RosUtil.js) for ROS-related extensions).
Example -> https://github.com/Affonso-Gui/scratch3-ros-vm#develop-a-library-for-your-own-robot

If you have already done quite some work on your custom extensions you can also try to git merge this branch into your developing branch, but you should be prepared to solve some conflicts, since this repository is not quite up to date with the LLK one.
